server:
  port: 8080

discodeit:
  repository:
    type: File
    fileDirectory: src/main/java/com/sprint/mission/discodeit/repository/file/data

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # DB 접속 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  # JPA 설정
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#로그 설정
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    path: /api-docs

